export const LIST_POST = 'LIST_POST';
export const LIST_POST_SUCCESS = 'LIST_POST_SUCCESS';
export const LIST_POST_FAIL = 'LIST_POST_FAIL';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_UPDATE_SUCCESS = 'POST_EDIT_SUCCESS';
